In [1]:
import pandas as pd

# Load the data and rename columns for clarity and to fix encoding
df = pd.read_csv('cfn_volumencreditocontingente_2025_enero-septiembre.csv', delimiter=';', encoding='latin-1')
df

,FECHA,SUBSISTEMA,ENTIDAD,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,PROVINCIA,CANTON,SECTOR,SUBSECTOR,ACTIVIDAD,NÚMERO DE OPERACIONES,MONTO OTORGADO
0,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,ALFREDO BAQUERIZO MORENO (JUJAN),INDUSTRIAS MANUFACTURERAS,ELABORACIÓN DE PRODUCTOS DE MOLINERÍA,MOLIENDA O PILADO DE ARROZ: PRODUCCIÓN DE ARRO...,11,106479.00
1,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,CAYAMBE,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,CULTIVO DE CEREALES (EXCEPTO ARROZ) LEGUMBRES ...,CULTIVO DE TRIGO,58,368374.01
2,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,CREDITO,REFINANCIADA,GUAYAS,GUAYAQUIL,INDUSTRIAS MANUFACTURERAS,FABRICACIÓN DE OTROS HILOS Y CABLES ELÉCTRICOS,FABRICACIÓN DE HILOS Y CABLES AISLADOS DE ACER...,1,4023690.74
3,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,CAYAMBE,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,CRÍA DE GANADO BOVINO Y BÚFALOS,PRODUCCIÓN DE LECHE CRUDA DE VACA,10,63340.35
4,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,ALFREDO BAQUERIZO MORENO (JUJAN),AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,CULTIVO DE ARROZ,CULTIVO DE ARROZ (INCLUIDO EL CULTIVO ORGÁNICO...,2,13068.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,07/31/2025,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO EMPRESARIAL,CREDITO,NOVADA,TUNGURAHUA,BAÑOS DE AGUA SANTA,ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE CO...,ACTIVIDADES DE ALOJAMIENTO PARA ESTANCIAS CORTAS,SERVICIOS DE ALOJAMIENTO PRESTADOS POR HOTELES...,2,96200.37
542,07/31/2025,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO PYMES,CREDITO,NOVADA,TUNGURAHUA,BAÑOS DE AGUA SANTA,ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE CO...,ACTIVIDADES DE ALOJAMIENTO PARA ESTANCIAS CORTAS,SERVICIOS DE ALOJAMIENTO PRESTADOS POR HOTELES...,1,86980.84
543,07/31/2025,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO PYMES,CREDITO,REESTRUCTURADA,EL ORO,PASAJE,"AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA",CULTIVO DE FRUTAS TROPICALES Y SUBTROPICALES,CULTIVO DE BANANOS Y PLÁTANOS,1,162673.90
544,07/31/2025,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO PYMES,CREDITO,REESTRUCTURADA,GUAYAS,DURAN,TRANSPORTE Y ALMACENAMIENTO,TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS POR...,TRANSPORTE TERRESTRE DE PASAJEROS POR SISTEMAS...,1,19331.52
545,08/31/2025,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO PYMES,CREDITO,REESTRUCTURADA,PICHINCHA,QUITO,CONSTRUCCIÓN,OTRAS ACTIVIDADES ESPECIALIZADAS DE CONSTRUCCIÓN,ALQUILER DE GRÚAS CON OPERADOR Y OTROS EQUIPOS...,1,330215.97

In [2]:
df['SUBSISTEMA'].unique()

array(['INSTITUCIONES FINANCIERAS PUBLICAS'], dtype=object)

In [3]:
df['ENTIDAD'].unique()

array(['CORPORACION FINANCIERA NACIONAL B.P.'], dtype=object)

In [4]:
df['TIPO DE CREDITO'].unique()

array(['PRODUCTIVO CORPORATIVO', 'PRODUCTIVO EMPRESARIAL',
       'PRODUCTIVO PYMES', 'MICROCREDITO DE ACUMULACION AMPLIADA'],
      dtype=object)

In [5]:
df['TIPO DE OPERACION'].unique()

array(['FACTORING', 'CREDITO', 'CONTINGENTE'], dtype=object)

In [6]:
df['ESTADO DE LA OPERACION'].unique()

array(['ORIGINAL', 'REFINANCIADA', 'REESTRUCTURADA', 'NOVADA'],
      dtype=object)

In [7]:
df['PROVINCIA'].unique()

array(['GUAYAS', 'PICHINCHA', 'MANABI', 'EL ORO', 'SANTA ELENA',
       'COTOPAXI', 'LOJA', 'LOS RIOS', 'AZUAY',
       'SANTO DOMINGO DE LOS TSÁCHILAS', 'CHIMBORAZO', 'ZAMORA CHINCHIPE',
       'ESMERALDAS', 'IMBABURA', 'TUNGURAHUA', 'BOLIVAR',
       'MORONA SANTIAGO', 'GALAPAGOS', 'ORELLANA', 'NAPO', 'CARCHI',
       'PASTAZA'], dtype=object)

In [8]:
df['CANTON'].unique()

array(['ALFREDO BAQUERIZO MORENO (JUJAN)', 'CAYAMBE', 'GUAYAQUIL',
       'MONTECRISTI', 'SANTA ROSA', 'SAN JACINTO DE YAGUACHI', 'JARAMIJO',
       'QUITO', 'PEDERNALES', 'SANTA ELENA', 'LATACUNGA', 'DURAN',
       'BALAO', 'LOJA', 'BABAHOYO', 'CUENCA', 'SALINAS', 'ARENILLAS',
       'SANTO DOMINGO', 'RIOBAMBA', 'PIÑAS', 'EL GUABO', 'QUEVEDO',
       'YANTZAZA', 'VINCES', 'MANTA', 'ESMERALDAS', 'LA LIBERTAD',
       'PUEBLO VIEJO', 'GENERAL ANTONIO ELIZALDE (BUCAY)', 'SALITRE',
       'MOCACHE', 'VENTANAS', 'PEDRO CARBO', 'ANTONIO ANTE', 'VALENCIA',
       'AMBATO', 'GUARANDA', 'SIMON BOLIVAR', 'MACHALA', 'MEJIA',
       'NARANJAL', 'LA MANA', 'PALORA', 'SANTA LUCIA', 'PLAYAS',
       'EL PANGUI', 'PORTOVIEJO', 'SALCEDO', 'PEDRO MONCAYO',
       'SAN VICENTE', 'IBARRA', 'BUENA FE', 'DAULE', 'URDANETA',
       'JIPIJAPA', 'PAJAN', 'PUYANGO', 'CORONEL MARCELINO MARIDUEÑA',
       'EL CARMEN', 'ATACAMES', 'SANTA CRUZ', 'CUMANDA', 'ORELLANA',
       'NABON', 'ISABELA', 'EL TRIUNFO', 'EL CHACO', 'ZAMORA', 'PUJILI',
       'QUININDE', 'HUAQUILLAS', 'PUERTO LOPEZ', 'CATAMAYO', 'CHONE',
       'MIRA', 'MUISNE', 'MOCHA', 'PICHINCHA', 'JAMA', 'SAMBORONDON',
       'RUMIÑAHUI', 'ROCAFUERTE', 'MILAGRO', 'SAN MIGUEL DE URCUQUI',
       'PALLATANGA', 'SAN PEDRO DE PELILEO', 'OTAVALO', 'NOBOL', 'BALZAR',
       'MONTALVO', 'SANTIAGO DE PILLARO', 'PASAJE', 'FLAVIO ALFARO',
       'ELOY ALFARO', 'TENA', 'COTACACHI', 'ZAPOTILLO',
       'LA JOYA DE LOS SACHAS', 'BAÑOS DE AGUA SANTA',
       'SAN MIGUEL DE LOS BANCOS', 'GUANO', 'MERA'], dtype=object)

In [9]:
df['SECTOR'].unique()

array(['INDUSTRIAS MANUFACTURERAS',
       'AGRICULTURA GANADERÍA  SILVICULTURA Y PESCA',
       'TRANSPORTE Y ALMACENAMIENTO', 'CONSTRUCCIÓN',
       'ACTIVIDADES PROFESIONALES CIENTÍFICAS Y TÉCNICAS',
       'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS',
       'ACTIVIDADES FINANCIERAS Y DE SEGUROS',
       'ACTIVIDADES INMOBILIARIAS',
       'COMERCIO AL POR MAYOR Y AL POR MENOR REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS',
       'EXPLOTACIÓN DE MINAS Y CANTERAS', 'INFORMACIÓN Y COMUNICACIÓN',
       'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO',
       'OTRAS ACTIVIDADES DE SERVICIOS',
       'SUMINISTRO DE ELECTRICIDAD GAS VAPOR Y AIRE ACONDICIONADO',
       'COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS',
       'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS',
       'AGRICULTURA, GANADERÍA,  SILVICULTURA Y PESCA',
       'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL',
       'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO',
       'ENSEÑANZA',
       'DISTRIBUCIÓN DE AGUA; ALCANTARILLADO, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO'],
      dtype=object)

In [10]:
df['NÚMERO DE OPERACIONES'].describe()

count    546.000000
mean       2.124542
std        6.846352
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max       83.000000
Name: NÚMERO DE OPERACIONES, dtype: float64

In [11]:
# By looking at the dataset, we can drop the columns SUBSECTOR and ACTIVIDAD, since they are grouped by SECTOR. 
df = df.drop(columns=['SUBSECTOR', 'ACTIVIDAD'])
df.head()

,FECHA,SUBSISTEMA,ENTIDAD,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,PROVINCIA,CANTON,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO
0,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,ALFREDO BAQUERIZO MORENO (JUJAN),INDUSTRIAS MANUFACTURERAS,11,106479.00
1,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,CAYAMBE,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,58,368374.01
2,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,CREDITO,REFINANCIADA,GUAYAS,GUAYAQUIL,INDUSTRIAS MANUFACTURERAS,1,4023690.74
3,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,CAYAMBE,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,10,63340.35
4,31/01/2022,INSTITUCIONES FINANCIERAS PUBLICAS,CORPORACION FINANCIERA NACIONAL B.P.,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,ALFREDO BAQUERIZO MORENO (JUJAN),AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,2,13068.00

In [12]:
# Columns SUBSISTEMA and ENTIDAD have only one unique value, so we can drop them as well.
df = df.drop(columns=['SUBSISTEMA', 'ENTIDAD'])
df.head()

,FECHA,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,PROVINCIA,CANTON,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO
0,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,ALFREDO BAQUERIZO MORENO (JUJAN),INDUSTRIAS MANUFACTURERAS,11,106479.00
1,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,CAYAMBE,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,58,368374.01
2,31/01/2022,PRODUCTIVO CORPORATIVO,CREDITO,REFINANCIADA,GUAYAS,GUAYAQUIL,INDUSTRIAS MANUFACTURERAS,1,4023690.74
3,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,CAYAMBE,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,10,63340.35
4,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,ALFREDO BAQUERIZO MORENO (JUJAN),AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,2,13068.00

In [13]:
# We can also drop the CANTON column, since it can be grouped by PROVINCIA.
df = df.drop(columns=['CANTON'])
df.head()

,FECHA,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,PROVINCIA,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO
0,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,INDUSTRIAS MANUFACTURERAS,11,106479.00
1,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,58,368374.01
2,31/01/2022,PRODUCTIVO CORPORATIVO,CREDITO,REFINANCIADA,GUAYAS,INDUSTRIAS MANUFACTURERAS,1,4023690.74
3,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,10,63340.35
4,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,2,13068.00

In [14]:
# We can group provinces into regions, since there are many provinces and it would be difficult to analyze them individually.
# Coastal region: Guayas, Manabí, El Oro, Santa Elena, Los Ríos, Esmeraldas
# Sierra region: Pichincha, Azuay, Cañar, Loja, Tungurahua, Chimborazo, Cotopaxi, Imbabura, Carchi, Bolívar, Napo, Pastaza, Sucumbíos, Orellana
# Amazon region: Morona Santiago, Zamora Chinchipe
# Insular region: Galápagos
coast = ['GUAYAS', 'MANABÍ', 'EL ORO', 'SANTA ELENA', 'LOS RÍOS', 'ESMERALDAS', 'SANTO DOMINGO DE LOS TSÁCHILAS']
sierra = ['PICHINCHA', 'AZUAY', 'CAÑAR', 'LOJA', 'TUNGURAHUA', 'CHIMBORAZO', 'COTOPAXI', 'IMBABURA', 'CARCHI', 'BOLÍVAR']
amazon = ['MORONA SANTIAGO', 'ZAMORA CHINCHIPE', 'SUCUMBÍOS', 'ORELLANA', 'NAPO', 'PASTAZA']
insular = ['GALÁPAGOS']
df['REGION'] = df['PROVINCIA'].apply(lambda x: 'COSTA' if x in coast else ('SIERRA' if x in sierra else ('AMAZONÍA' if x in amazon else 'INSULAR')))
df.head()

,FECHA,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,PROVINCIA,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO,REGION
0,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,INDUSTRIAS MANUFACTURERAS,11,106479.00,COSTA
1,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,58,368374.01,SIERRA
2,31/01/2022,PRODUCTIVO CORPORATIVO,CREDITO,REFINANCIADA,GUAYAS,INDUSTRIAS MANUFACTURERAS,1,4023690.74,COSTA
3,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,PICHINCHA,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,10,63340.35,SIERRA
4,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,GUAYAS,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,2,13068.00,COSTA

In [15]:
#We can substitute the Provincia column with the Region column, since it is more general and we can analyze the data by region instead of by province.
df = df.drop(columns=['PROVINCIA'])
df.head()

,FECHA,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO,REGION
0,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,INDUSTRIAS MANUFACTURERAS,11,106479.00,COSTA
1,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,58,368374.01,SIERRA
2,31/01/2022,PRODUCTIVO CORPORATIVO,CREDITO,REFINANCIADA,INDUSTRIAS MANUFACTURERAS,1,4023690.74,COSTA
3,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,10,63340.35,SIERRA
4,31/01/2022,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,2,13068.00,COSTA

In [16]:
#We can drop FECHA since it is not relevant for our analysis and it would be difficult to analyze the data by date.
df = df.drop(columns=['FECHA'])
df.head()

,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO,REGION
0,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,INDUSTRIAS MANUFACTURERAS,11,106479.00,COSTA
1,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,58,368374.01,SIERRA
2,PRODUCTIVO CORPORATIVO,CREDITO,REFINANCIADA,INDUSTRIAS MANUFACTURERAS,1,4023690.74,COSTA
3,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,10,63340.35,SIERRA
4,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,AGRICULTURA GANADERÍA SILVICULTURA Y PESCA,2,13068.00,COSTA

In [17]:
# We group SECTOR into 4 categories (Primary: extraction, Secondary: manufacturing, Tertiary: services, Quaternary: knowledge/IT)
mapeo_sectores = {
    'AGRICULTURA GANADERÍA  SILVICULTURA Y PESCA': 'Primary',
    'AGRICULTURA, GANADERÍA,  SILVICULTURA Y PESCA': 'Primary',
    'EXPLOTACIÓN DE MINAS Y CANTERAS': 'Primary',
    'INDUSTRIAS MANUFACTURERAS': 'Secondary',
    'CONSTRUCCIÓN': 'Secondary',
    'SUMINISTRO DE ELECTRICIDAD GAS VAPOR Y AIRE ACONDICIONADO': 'Secondary',
    'SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO': 'Secondary',
    'DISTRIBUCIÓN DE AGUA; ALCANTARILLADO, GESTIÓN DE DESECHOS Y ACTIVIDADES DE SANEAMIENTO': 'Secondary',
    'COMERCIO AL POR MAYOR Y AL POR MENOR REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS': 'Tertiary',
    'COMERCIO AL POR MAYOR Y AL POR MENOR; REPARACIÓN DE VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS': 'Tertiary',
    'TRANSPORTE Y ALMACENAMIENTO': 'Tertiary',
    'ACTIVIDADES FINANCIERAS Y DE SEGUROS': 'Tertiary',
    'ACTIVIDADES INMOBILIARIAS': 'Tertiary',
    'ACTIVIDADES DE ALOJAMIENTO Y DE SERVICIO DE COMIDAS': 'Tertiary',
    'ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO': 'Tertiary',
    'ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL': 'Tertiary',
    'ENSEÑANZA': 'Tertiary',
    'OTRAS ACTIVIDADES DE SERVICIOS': 'Tertiary',
    'INFORMACIÓN Y COMUNICACIÓN': 'Quaternary',
    'ACTIVIDADES PROFESIONALES CIENTÍFICAS Y TÉCNICAS': 'Quaternary',
    'ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS': 'Quaternary'
}
df['SECTOR'] = df['SECTOR'].map(mapeo_sectores)
df.head()

,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO,REGION
0,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,Secondary,11,106479.00,COSTA
1,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,Primary,58,368374.01,SIERRA
2,PRODUCTIVO CORPORATIVO,CREDITO,REFINANCIADA,Secondary,1,4023690.74,COSTA
3,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,Primary,10,63340.35,SIERRA
4,PRODUCTIVO CORPORATIVO,FACTORING,ORIGINAL,Primary,2,13068.00,COSTA

In [18]:
# We translate to english the elements of the TIPO DE CREDITO column for better understanding. 
# PRODUCTIVO CORPORATIVO', 'PRODUCTIVO EMPRESARIAL', 'PRODUCTIVO PYMES', 'MICROCREDITO DE ACUMULACION AMPLIADA'
mapeo_creditos = {
    'PRODUCTIVO CORPORATIVO': 'Corporate',
    'PRODUCTIVO EMPRESARIAL': 'Business',
    'PRODUCTIVO PYMES': 'SMEs',
    'MICROCREDITO DE ACUMULACION AMPLIADA': 'Microcredit'
}
df['TIPO DE CREDITO'] = df['TIPO DE CREDITO'].map(mapeo_creditos)
df.head()

,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO,REGION
0,Corporate,FACTORING,ORIGINAL,Secondary,11,106479.00,COSTA
1,Corporate,FACTORING,ORIGINAL,Primary,58,368374.01,SIERRA
2,Corporate,CREDITO,REFINANCIADA,Secondary,1,4023690.74,COSTA
3,Corporate,FACTORING,ORIGINAL,Primary,10,63340.35,SIERRA
4,Corporate,FACTORING,ORIGINAL,Primary,2,13068.00,COSTA

In [19]:
 # We translate to english the elements of the TIPO DE OPERACION column for better understanding.
# 'FACTORING', 'CREDITO', 'CONTINGENTE'
mapeo_operaciones = {
    'FACTORING': 'Factoring',
    'CREDITO': 'Credit',
    'CONTINGENTE': 'Contingent'
}
df['TIPO DE OPERACION'] = df['TIPO DE OPERACION'].map(mapeo_operaciones)
df.head()

,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO,REGION
0,Corporate,Factoring,ORIGINAL,Secondary,11,106479.00,COSTA
1,Corporate,Factoring,ORIGINAL,Primary,58,368374.01,SIERRA
2,Corporate,Credit,REFINANCIADA,Secondary,1,4023690.74,COSTA
3,Corporate,Factoring,ORIGINAL,Primary,10,63340.35,SIERRA
4,Corporate,Factoring,ORIGINAL,Primary,2,13068.00,COSTA

In [20]:
# We translate ESTADO DE LA OPERACION column to english as well. 'ORIGINAL', 'REFINANCIADA', 'REESTRUCTURADA', 'NOVADA'
mapeo_estados = {
    'ORIGINAL': 'Original',
    'REFINANCIADA': 'Refinanced',
    'REESTRUCTURADA': 'Restructured',
    'NOVADA': 'Novated'
}
df['ESTADO DE LA OPERACION'] = df['ESTADO DE LA OPERACION'].map(mapeo_estados)
df.head()

,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,SECTOR,NÚMERO DE OPERACIONES,MONTO OTORGADO,REGION
0,Corporate,Factoring,Original,Secondary,11,106479.00,COSTA
1,Corporate,Factoring,Original,Primary,58,368374.01,SIERRA
2,Corporate,Credit,Refinanced,Secondary,1,4023690.74,COSTA
3,Corporate,Factoring,Original,Primary,10,63340.35,SIERRA
4,Corporate,Factoring,Original,Primary,2,13068.00,COSTA

In [21]:
# We can join rows if they have the same values in all columns except for NÚMERO DE OPERACIONES, and MONTO OTORGADO, in which case we can sum these two columns.
df = df.groupby(['REGION', 'SECTOR', 'TIPO DE CREDITO', 'TIPO DE OPERACION', 'ESTADO DE LA OPERACION']).agg({'NÚMERO DE OPERACIONES': 'sum', 'MONTO OTORGADO': 'sum'}).reset_index()
df.head()

,REGION,SECTOR,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,NÚMERO DE OPERACIONES,MONTO OTORGADO
0,AMAZONÍA,Primary,Business,Credit,Novated,1,118181.85
1,AMAZONÍA,Primary,Business,Credit,Restructured,1,231651.52
2,AMAZONÍA,Primary,Corporate,Credit,Restructured,1,861907.27
3,AMAZONÍA,Primary,SMEs,Contingent,Restructured,2,502467.40
4,AMAZONÍA,Primary,SMEs,Credit,Novated,2,160000.00

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 121 entries, 0 to 120
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   REGION                  121 non-null    object
 1   SECTOR                  121 non-null    object
 2   TIPO DE CREDITO         121 non-null    object
 3   TIPO DE OPERACION       121 non-null    object
 4   ESTADO DE LA OPERACION  121 non-null    object
 5   NÚMERO DE OPERACIONES   121 non-null    int64
 6   MONTO OTORGADO          121 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 6.7+ KB

In [24]:
# we can transform MONTO OTORGADO  with logarithm to reduce the skewness of the data and make it more normal, which can help with the analysis and modeling.
import numpy as np
df['MONTO OTORGADO'] = np.log(df['MONTO OTORGADO'])
df.head()

,REGION,SECTOR,TIPO DE CREDITO,TIPO DE OPERACION,ESTADO DE LA OPERACION,NÚMERO DE OPERACIONES,MONTO OTORGADO
0,AMAZONÍA,Primary,Business,Credit,Novated,1,11.679980
1,AMAZONÍA,Primary,Business,Credit,Restructured,1,12.352989
2,AMAZONÍA,Primary,Corporate,Credit,Restructured,1,13.666903
3,AMAZONÍA,Primary,SMEs,Contingent,Restructured,2,13.127286
4,AMAZONÍA,Primary,SMEs,Credit,Novated,2,11.982929

In [25]:
# We change the name of the columns to english for better understanding and analysis.
df = df.rename(columns={'REGION': 'Region', 'SECTOR': 'Sector', 'TIPO DE CREDITO': 'Credit Type', 'TIPO DE OPERACION': 'Operation Type', 'ESTADO DE LA OPERACION': 'Operation Status', 'NÚMERO DE OPERACIONES': 'Number of Operations', 'MONTO OTORGADO': 'Log-Amount Granted'})
df.head()

,Region,Sector,Credit Type,Operation Type,Operation Status,Number of Operations,Log-Amount Granted
0,AMAZONÍA,Primary,Business,Credit,Novated,1,11.679980
1,AMAZONÍA,Primary,Business,Credit,Restructured,1,12.352989
2,AMAZONÍA,Primary,Corporate,Credit,Restructured,1,13.666903
3,AMAZONÍA,Primary,SMEs,Contingent,Restructured,2,13.127286
4,AMAZONÍA,Primary,SMEs,Credit,Novated,2,11.982929

In [26]:
# Save the cleaned dataset to a new CSV file
df.to_csv('cleaned_cfn_volumencreditocontingente_2025_enero-septiembre.csv', index=False)